### ISSUE TITLE
ctrl+l not working

### ISSUE THREAD

**Issue by KaneRoot** [allenh1/YaSh#33]
Hello, I installed yash from the latest release and it works as expected excepts for ctrl+l that do not clean my screen.

What should I test? How to debug?

Thanks!

**Comment by allenh1** [comment]
@KaneRoot Hey! Sorry, this somehow got burried in my GitHub notifications. Glad the shell's working for you!

As for your `ctrl+l` question, I'm curious which operating system you're on? Which terminal emulator are you using (such as gnome-shell, etc), and if you're doing this over ssh or something?

**Comment by allenh1** [comment]
@KaneRoot Actually, I just realized that `ctrl + l` is not in the latest release, [it turns out](https://github.com/allenh1/YaSh/compare/v0.0.8...master).

I'll draft a new release and push it out in the next couple of days. You can use the master revision in the meantime, however, if you want to use `ctrl + l` or `ctrl + w`.

**Comment by allenh1** [comment]
@KaneRoot I've released the next version, [version 0.0.9](https://github.com/allenh1/YaSh/releases/tag/v0.0.9), with your requested keyboard shortcuts!

Please reopen this if you have any issues still!
